#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

# cookbook 'chef-client'

cookbook 'apt'
cookbook 'apache2', '>= 1.11.0'

cookbook 'openclerk',
  :git => 'https://github.com/soundasleep/openclerk-cookbook'

cookbook 'composer',
  :git => 'git://github.com/Morphodo/chef-composer.git'

cookbook 'grunt_cookbook',
  :git => 'git://github.com/MattSurabian/grunt_cookbook.git'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
